### ISSUE TITLE
Try to set up uv workspaces

### ISSUE THREAD

**Issue by vrslev** [modern-python/modern-di#3]
https://docs.astral.sh/uv/concepts/workspaces/

@lesnik512: 

> uv-workspaces кажется не подходит. Он вроде юзает одно окружение в корне и постоянно его обновляет в зависимости от контекста. По крайней мере у меня не завелась с ним работа

**Comment by lesnik512** [comment]
I didn't found a way to call `uv sync` for all workspaces at once

**Comment by lesnik512** [comment]
I have added workspaces, but this is still valid

> I hadn't found a way to call uv sync for all workspaces at once
